/*****************************************************************************
* Model: blinky.qm
* File:  ./serial_debug.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::serial_debug.c} .....................................................*/
#include "qpc.h"
#include "application.h"
#include "blinky.h"
#include "bsp.h"

Q_DEFINE_THIS_FILE

/*${AOs::SerialDebug} ......................................................*/
typedef struct {
/* protected: */
    QActive super;
} SerialDebug;

/* protected: */
static QState SerialDebug_initial(SerialDebug * const me, QEvt const * const e);
static QState SerialDebug_standby(SerialDebug * const me, QEvt const * const e);


/* Local objects */
static SerialDebug l_serial_debug;

/* Global objects */
QMActive * const AO_SerialDebug = &l_serial_debug.super;

/* Blinky definition */
/*${AOs::SerialDebug_ctor} .................................................*/
void SerialDebug_ctor(void) {
    SerialDebug * const me = &l_serial_debug;
    QActive_ctor(&me->super, Q_STATE_CAST(&SerialDebug_initial));
}
/*${AOs::SerialDebug} ......................................................*/
/*${AOs::SerialDebug::SM} ..................................................*/
static QState SerialDebug_initial(SerialDebug * const me, QEvt const * const e) {
    /* ${AOs::SerialDebug::SM::initial} */
    return Q_TRAN(&SerialDebug_standby);
}
/*${AOs::SerialDebug::SM::standby} .........................................*/
static QState SerialDebug_standby(SerialDebug * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::SerialDebug::SM::standby::SERIAL_DEBUG_MSG} */
        case SERIAL_DEBUG_MSG_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

