/*****************************************************************************
* Model: blinky.qm
* File:  ./serial_debug.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::serial_debug.c} .....................................................*/
#include "qpc.h"
#include "application.h"
#include "blinky.h"
#include "bsp.h"

Q_DEFINE_THIS_FILE

/*${AOs::SerialDebug} ......................................................*/
typedef struct {
/* protected: */
    QMActive super;
} SerialDebug;

/* protected: */
static QState SerialDebug_initial(SerialDebug * const me, QEvt const * const e);
static QState SerialDebug_standby  (SerialDebug * const me, QEvt const * const e);
static QMState const SerialDebug_standby_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&SerialDebug_standby),
    Q_ACTION_CAST(0), /* no entry action */
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};


/* Local objects */
static SerialDebug l_serial_debug;

/* Global objects */
QMActive * const AO_SerialDebug = &l_serial_debug.super;

/* Blinky definition */
/*${AOs::SerialDebug_ctor} .................................................*/
void SerialDebug_ctor(void) {
    SerialDebug * const me = &l_serial_debug;
    QMActive_ctor(&me->super, Q_STATE_CAST(&SerialDebug_initial));
}
/*${AOs::SerialDebug} ......................................................*/
/*${AOs::SerialDebug::SM} ..................................................*/
static QState SerialDebug_initial(SerialDebug * const me, QEvt const * const e) {
    static QMTranActTable const tatbl_ = { /* transition-action table */
        &SerialDebug_standby_s,
        {
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${AOs::SerialDebug::SM::initial} */
    QActive_subscribe(&me->super, SERIAL_DEBUG_MSG_SIG);

    //SerialDebugMsgEvt *pe;
    //pe = Q_NEW(SerialDebugMsgEvt, SERIAL_DEBUG_MSG_SIG);
    //pe->data[0] = 0xAB;
    //QF_PUBLISH(&pe->super, me);
    return QM_TRAN_INIT(&tatbl_);
}
/*${AOs::SerialDebug::SM::standby} .........................................*/
/* ${AOs::SerialDebug::SM::standby} */
static QState SerialDebug_standby(SerialDebug * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::SerialDebug::SM::standby::SERIAL_DEBUG_MSG} */
        case SERIAL_DEBUG_MSG_SIG: {
            static QMTranActTable const tatbl_ = { /* transition-action table */
                &SerialDebug_standby_s,
                {
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

